### ISSUE TITLE
Search entry box looks odd

### ISSUE THREAD

**Issue by quozl** [sugarlabs/browse-activity#115]
On Ubuntu 20.10 and 22.04 the search entry box looks odd; a blue outline is incomplete at corners.

![Screenshot_ugg_2020-10-24_15:25:32](https://user-images.githubusercontent.com/2936481/97067808-397fe100-160d-11eb-87b2-7935636f47a1.png)

**Comment by sarthak0527** [comment]
Hey I would like to work on this and would like to change the UI for this.

**Comment by quozl** [comment]
Me too.  Please review my pull request; is there a better way to do it that does not remove the curved entry box style we use in Sugar?

**Comment by quozl** [comment]
39c41b0
