### ISSUE TITLE
WebKit2 is terribly slow with keyboard input

### ISSUE THREAD

**Issue by samdroid-apps** [sugarlabs/browse-activity#35]
Tested on the login form of gmail and my school's LMS

When you type, there is a huge lag between you pressing the key and it being entered.  Everything looks like it has the slow type effect going - all the key presses are spaced out 500ms.

The rest of the ui (eg. mousing over a dropdown menu in the LMS site) is very snappy.  But not the typing.  Is this our fault or is it a webkit bug?

**Comment by quozl** [comment]
Reproduced with WebKit 2.10.9 on Ubuntu 16.04, but today's security update to WebKit 2.12.5 has fixed it.  If you no longer see it, then the issue can be closed.

**Comment by quozl** [comment]
Nobody else has reported it, and the new WebKit package fixed it, closing.
