### ISSUE TITLE
general license wrong: some parts are licensed as GPL-3+

### ISSUE THREAD

**Issue by jonassmedegaard** [sugarlabs/browse-activity#41]
General license - e.g. in metadata for Github - is GPL-2+, but some parts (progresstoolbutton.py) is GPL-3+ - i.e. is incompatible with the overall license.

I believe you should adjust the metadata llicense to reflect not the most common license used (GPL-2+) but instead the effective license that all code is licensed to migrate to: GPL-3+.

**Comment by jonassmedegaard** [comment]
In other words: This issue is *not* that specific license statements need to be changed - only "summary" statements about the overall/effective licensing of the project as a whole.

**Comment by icarito** [comment]
There isn't a *license* metadata setting in Github. If you click the GPL-2.0 link on the top, it takes you to the file "COPYING" which indeed is GPL-2. I guess this file should be updated to GPL-3.0 and Github should detect it.

**Comment by jonassmedegaard** [comment]
Excerpts from Sebastian Silva's message of December 12, 2016 2:50 pm:
> There isn't a *license* metadata setting in Github. If you click the GPL-2.0 link on the top, it takes you to the file "COPYING" which indeed is GPL-2. I guess this file should be updated to GPL-3.0 and Github should detect it.

By your description of relationship between project top link and COPYING
file contents, arguably that file *is* metadata for Github.


 - Jonas
-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by icarito** [comment]
On 12/12/16 08:59, Jonas Smedegaard wrote:
> By your description of relationship between project top link and COPYING
> file contents, arguably that file *is* metadata for Github.
Always the nitpicker :-D

While we are at it, I didn't say purely "metadata", I said "metadata
setting" - meaning a configuration knob or something, which is what I
thought you meant because of course otherwise you'd just have submitted
a patch ;-)

**Comment by icarito** [comment]
Jonas here's a patch in queue for merge. Let me know if I can be of help. Regards!

**Comment by quozl** [comment]
@jonassmedegaard, is this issue fixed now?

* COPYING is GPL-3+, and as consequence GitHub shows repository as GPL-3.0,
* several Python source files are GPL-2+,
* activity.info shows GPL-2.0+ source code license and CC0-1.0 for metadata.

It's a bit of a mess!

**Comment by jonassmedegaard** [comment]
Looks fine to me.

And I disagree: Does not look messy to me at all.  On the contrary, projects with many contributors and perfectly aligned licensing looks suspicious/unreal/manipulated to me ;-)

**Comment by quozl** [comment]
Heh, you're so right.  Closing.
