### ISSUE TITLE
broken stop button

### ISSUE THREAD

**Issue by jonassmedegaard** [sugarlabs/browse-activity#42]
It seems that the stop button is broken - related code contains what seems to be a typo (missing "E"):

if web_error.code == WebKit2.NetworkError.CANCLLED:

NB! I have not tested if code works or not, only noticed by skimming through source commits.

**Comment by jonassmedegaard** [comment]
Not only theory:

Traceback (most recent call last):
  File "/usr/share/sugar/activities/Browse.activity/browser.py", line 822, in __load_failed_cb
    if web_error.code == WebKit2.NetworkError.CANCLLED:
AttributeError: type object 'NetworkError' has no attribute 'CANCLLED'

**Comment by quozl** [comment]
aadc1703fb5207e17bc75974d932d401d795d53c fixed this, so you're needing a release after 200.

**Comment by jonassmedegaard** [comment]
Excerpts from James Cameron's message of December 12, 2016 7:29 pm:
> aadc1703fb5207e17bc75974d932d401d795d53c fixed this, so you're needing a release after 200.

Thanks.  That worked!

 - Jonas
-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private
