### ISSUE TITLE
Every PDF is downloaded twice

### ISSUE THREAD

**Issue by quozl** [sugarlabs/browse-activity#54]
In browser.py `__decide_policy_cb` when the MIME Type is `application/pdf` the in-progress or completed GET request is abandoned and a second GET request is made by the PDF viewer.

This uses more internet bandwidth and causes double-counting in server logs.

**Comment by nswarup14** [comment]
Extensively tested the activity at https://github.com/sugarlabs/browse-activity/commit/540c93fa5fe4ca1a741c6460abed2607aa8a8078, but the PDF file is getting downloaded just once.

Steps taken to reproduce:
1) Open Browse
2) Google search 'Machine Learning paper pdf'
3) Click on the first link that is a PDF
4) Download begins and PDF opens in a new tab
5) Close tab and `Stop` activity
6) Check Journal, only one instance of the PDF is shown as per attached screenshot.

**Comment by pro-panda** [comment]
@nswarup14 Thanks for testing

The issue description is suggestive of the problem.
From memory, here is what happens when you try to open a URL pointing to a PDF,
 - `GET` request with URL pointing to the PDF is made
 - from the request response, if the `MIME` type is `application/pdf`, then
 - control is passed to the pdf viewer, which in turn makes a **new** request, and stores the pdf from the response received in the journal

**Comment by quozl** [comment]
Use an HTTP server to verify there is only one request.  For instance; `mkdir`, `cp` a PDF, `python -m SimpleHTTPServer`, and open http://localhost:8000/

**Comment by nswarup14** [comment]
@quozl 
I followed your test case to verify the number of GET requests.
And there was only one 😄 

I have attached screenshot for reference
![Screenshot (26)](https://user-images.githubusercontent.com/34597895/61523377-e1355900-aa31-11e9-8d4d-8887d95555ae.png)

Thanks.

**Comment by quozl** [comment]
Thanks.  Just to remove ambiguity, the test was with which git hash?

Looking forward to your updated commit messages on
https://github.com/sugarlabs/browse-activity/pull/102

**Comment by nswarup14** [comment]
@quozl 
I tested with https://github.com/sugarlabs/browse-activity/pull/102/commits/2afe8786713047c363defc409fa93aef72dc101e.

I shall update the commit messages.
Thanks
