### ISSUE TITLE
Unable to load webpages in Browse

### ISSUE THREAD

**Issue by iamutkarshtiwari** [sugarlabs/browse-activity#68]
I am trying to load pages like google.com in Browse but it seems to get stuck. Below is the attached log for the activity session.

[org.laptop.WebActivity-1.log](https://github.com/sugarlabs/browse-activity/files/1558526/org.laptop.WebActivity-1.log)

**Comment by quozl** [comment]
Thanks for your problem report.  You have in your logs;

```
Traceback (most recent call last):
  File "/home/broot/sugar-build/build/out/install/share/sugar/activities/Browse.activity/webtoolbar.py", line 515, in __key_press_event_cb
    self._tabbed_view.current_browser.loading_uri = entry.props.text
AttributeError: 'NoneType' object has no attribute 'loading_uri'
```

But as can be seen from https://github.com/sugarlabs/browse-activity/blob/master/webtoolbar.py#L515 this does not align.

You have different Browse source code.

Please ensure you are using the latest Browse source code and try again.

Also, any problems with `broot` or `sugar-build`; please raise them in the respective repositories, as those environments are not targeted by Browse.  That is to say, when I commit changes to Browse, I don't test for or care if they break in those environments.  I only care if they break in native or packaged Sugar environments.
