### ISSUE TITLE
Invalid link in README under "How to develop?"

### ISSUE THREAD

**Issue by DipanshKhandelwal** [sugarlabs/browse-activity#71]
Link - [setup a development environment for Sugar desktop](https://developer.sugarlabs.org/dev-environment.md.html) under "How to develop?" in README doesn't work.

**Comment by Pro-Panda** [comment]
https://developer.sugarlabs.org is **partially** moved to Github

More such broken links can be looked in [here](https://github.com/search?p=2&q=org%3Asugarlabs+developer.sugarlabs.org&type=Code).

@quozl, should all these be fixed manually, or a redirect link be provided on all such broken pages itself, or a better alternative.

**Comment by quozl** [comment]
I've removed the link.

I've used a slightly [different search](https://github.com/search?utf8=%E2%9C%93&q=org%3Asugarlabs+%22developer.sugarlabs.org%2F%22&type=Code) and haven't found any that I care about enough to change them.
